name = "PosteriorStats"
uuid = "7f36be82-ad55-44ba-a5c0-b8b5480d7aa5"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "0.4.7"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
IrrationalConstants = "92d709cd-6900-40b7-9082-c6be49f344b6"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NLSolversBase = "d41bc354-129a-5804-8e4c-c37616107c6c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PSIS = "ce719bf2-d5d0-4fb9-925d-10a81b42ad04"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
BSON = "0.3"
Compat = "4.10"
DimensionalData = "0.24, 0.25, 0.26, 0.27, 0.28, 0.29"
Distributions = "0.25.57"
DocStringExtensions = "0.8, 0.9"
FFTW = "1.6.0"
FiniteDifferences = "0.12.17"
GLM = "1.8.0"
IntervalSets = "0.5, 0.6, 0.7"
IrrationalConstants = "0.1, 0.2"
IteratorInterfaceExtensions = "1"
KernelDensity = "0.6.3"
LinearAlgebra = "1"
LogExpFunctions = "0.3.3"
MCMCDiagnosticTools = "0.3.4"
Markdown = "1"
NLSolversBase = "7.8.0, 8"
OffsetArrays = "1.1.3"
Optim = "1.7.2, 2"
OrderedCollections = "1.3.0"
PDMats = "0.11.11"
PSIS = "0.9.1"
PrettyTables = "2.1, 3"
Printf = "1"
Random = "1"
Roots = "1, 2"
Setfield = "1"
SpecialFunctions = "1.2, 2"
Statistics = "1"
StatsBase = "0.33.17, 0.34"
TableTraits = "1"
Tables = "1.9"
julia = "1.10"

[extras]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BSON", "DimensionalData", "FiniteDifferences", "GLM", "Logging", "OffsetArrays", "Test"]
